// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/biz.proto

// 对应 Biz 业务层协议

package biz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举：消息类型，区分群消息和私聊消息
type EnumCLawMsgType int32

const (
	EnumCLawMsgType_CLAW_MSG_UNKNOWN EnumCLawMsgType = 0 // 未知类型
	EnumCLawMsgType_CLAW_MSG_GROUP   EnumCLawMsgType = 1 // 群消息
	EnumCLawMsgType_CLAW_MSG_PRIVATE EnumCLawMsgType = 2 // 私聊消息
)

// Enum value maps for EnumCLawMsgType.
var (
	EnumCLawMsgType_name = map[int32]string{
		0: "CLAW_MSG_UNKNOWN",
		1: "CLAW_MSG_GROUP",
		2: "CLAW_MSG_PRIVATE",
	}
	EnumCLawMsgType_value = map[string]int32{
		"CLAW_MSG_UNKNOWN": 0,
		"CLAW_MSG_GROUP":   1,
		"CLAW_MSG_PRIVATE": 2,
	}
)

func (x EnumCLawMsgType) Enum() *EnumCLawMsgType {
	p := new(EnumCLawMsgType)
	*p = x
	return p
}

func (x EnumCLawMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumCLawMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_biz_proto_enumTypes[0].Descriptor()
}

func (EnumCLawMsgType) Type() protoreflect.EnumType {
	return &file_proto_biz_proto_enumTypes[0]
}

func (x EnumCLawMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumCLawMsgType.Descriptor instead.
func (EnumCLawMsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{0}
}

// 枚举：心跳状态
type EnumHeartbeat int32

const (
	EnumHeartbeat_HEARTBEAT_UNKNOWN EnumHeartbeat = 0 // 未知状态
	EnumHeartbeat_HEARTBEAT_RUNNING EnumHeartbeat = 1 // 运行中
	EnumHeartbeat_HEARTBEAT_FINISH  EnumHeartbeat = 2 // 已完成
)

// Enum value maps for EnumHeartbeat.
var (
	EnumHeartbeat_name = map[int32]string{
		0: "HEARTBEAT_UNKNOWN",
		1: "HEARTBEAT_RUNNING",
		2: "HEARTBEAT_FINISH",
	}
	EnumHeartbeat_value = map[string]int32{
		"HEARTBEAT_UNKNOWN": 0,
		"HEARTBEAT_RUNNING": 1,
		"HEARTBEAT_FINISH":  2,
	}
)

func (x EnumHeartbeat) Enum() *EnumHeartbeat {
	p := new(EnumHeartbeat)
	*p = x
	return p
}

func (x EnumHeartbeat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumHeartbeat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_biz_proto_enumTypes[1].Descriptor()
}

func (EnumHeartbeat) Type() protoreflect.EnumType {
	return &file_proto_biz_proto_enumTypes[1]
}

func (x EnumHeartbeat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumHeartbeat.Descriptor instead.
func (EnumHeartbeat) EnumDescriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{1}
}

// 消息序号信息，用于标识消息的序列号和消息ID
type ImMsgSeq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgSeq        uint64                 `protobuf:"varint,1,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"` // 消息序列号
	MsgId         string                 `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`    // 消息ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImMsgSeq) Reset() {
	*x = ImMsgSeq{}
	mi := &file_proto_biz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImMsgSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImMsgSeq) ProtoMessage() {}

func (x *ImMsgSeq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImMsgSeq.ProtoReflect.Descriptor instead.
func (*ImMsgSeq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{0}
}

func (x *ImMsgSeq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *ImMsgSeq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// 图片信息，包含图片的元数据
type ImImageInfoArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`     // 图片类型
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`     // 图片大小
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`   // 图片宽度
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"` // 图片高度
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`        // 图片URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImImageInfoArray) Reset() {
	*x = ImImageInfoArray{}
	mi := &file_proto_biz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImImageInfoArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImImageInfoArray) ProtoMessage() {}

func (x *ImImageInfoArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImImageInfoArray.ProtoReflect.Descriptor instead.
func (*ImImageInfoArray) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{1}
}

func (x *ImImageInfoArray) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ImImageInfoArray) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImImageInfoArray) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImImageInfoArray) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImImageInfoArray) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 消息具体内容，包含文本、图片、文件等多种消息类型
type MsgContent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                     // 文本内容
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                     // 消息唯一标识
	ImageFormat    uint32                 `protobuf:"varint,3,opt,name=imageFormat,proto3" json:"imageFormat,omitempty"`      // 图片格式
	Data           string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                     // 数据内容
	Desc           string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`                     // 描述信息
	Ext            string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`                       // 扩展信息
	Sound          string                 `protobuf:"bytes,7,opt,name=sound,proto3" json:"sound,omitempty"`                   // 声音/语音信息
	ImageInfoArray []*ImImageInfoArray    `protobuf:"bytes,8,rep,name=imageInfoArray,proto3" json:"imageInfoArray,omitempty"` // 图片信息数组
	Index          uint32                 `protobuf:"varint,9,opt,name=index,proto3" json:"index,omitempty"`                  // 索引
	Url            string                 `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`                      // URL地址
	FileSize       uint32                 `protobuf:"varint,11,opt,name=fileSize,proto3" json:"fileSize,omitempty"`           // 文件大小
	FileName       string                 `protobuf:"bytes,12,opt,name=fileName,proto3" json:"fileName,omitempty"`            // 文件名称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgContent) Reset() {
	*x = MsgContent{}
	mi := &file_proto_biz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContent) ProtoMessage() {}

func (x *MsgContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContent.ProtoReflect.Descriptor instead.
func (*MsgContent) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{2}
}

func (x *MsgContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MsgContent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MsgContent) GetImageFormat() uint32 {
	if x != nil {
		return x.ImageFormat
	}
	return 0
}

func (x *MsgContent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MsgContent) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MsgContent) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *MsgContent) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *MsgContent) GetImageInfoArray() []*ImImageInfoArray {
	if x != nil {
		return x.ImageInfoArray
	}
	return nil
}

func (x *MsgContent) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MsgContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MsgContent) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MsgContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 消息体元素，包含消息类型和消息内容
type MsgBodyElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`       // 消息类型，如 "TIMTextElem", "TIMImageElem" 等
	MsgContent    *MsgContent            `protobuf:"bytes,2,opt,name=msgContent,proto3" json:"msgContent,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBodyElement) Reset() {
	*x = MsgBodyElement{}
	mi := &file_proto_biz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBodyElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBodyElement) ProtoMessage() {}

func (x *MsgBodyElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBodyElement.ProtoReflect.Descriptor instead.
func (*MsgBodyElement) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{3}
}

func (x *MsgBodyElement) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *MsgBodyElement) GetMsgContent() *MsgContent {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

// 日志扩展信息，用于传递追踪信息
type LogInfoExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"` // 追踪ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInfoExt) Reset() {
	*x = LogInfoExt{}
	mi := &file_proto_biz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInfoExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInfoExt) ProtoMessage() {}

func (x *LogInfoExt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInfoExt.ProtoReflect.Descriptor instead.
func (*LogInfoExt) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{4}
}

func (x *LogInfoExt) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 发送C2C消息请求，用于向单个用户发送消息
type SendC2CMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`             // 消息ID
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`     // 接收者账号
	FromAccount   string                 `protobuf:"bytes,3,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"` // 发送者账号
	MsgRandom     uint32                 `protobuf:"varint,4,opt,name=msgRandom,proto3" json:"msgRandom,omitempty"`    // 消息随机数
	MsgBody       []*MsgBodyElement      `protobuf:"bytes,5,rep,name=msgBody,proto3" json:"msgBody,omitempty"`         // 消息体列表
	GroupCode     string                 `protobuf:"bytes,6,opt,name=groupCode,proto3" json:"groupCode,omitempty"`     // 群号（私聊时使用）
	MsgSeq        uint64                 `protobuf:"varint,7,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`          // 消息序列号
	LogExt        *LogInfoExt            `protobuf:"bytes,8,opt,name=logExt,proto3" json:"logExt,omitempty"`           // 日志扩展信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendC2CMessageReq) Reset() {
	*x = SendC2CMessageReq{}
	mi := &file_proto_biz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendC2CMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendC2CMessageReq) ProtoMessage() {}

func (x *SendC2CMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendC2CMessageReq.ProtoReflect.Descriptor instead.
func (*SendC2CMessageReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{5}
}

func (x *SendC2CMessageReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendC2CMessageReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendC2CMessageReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendC2CMessageReq) GetMsgRandom() uint32 {
	if x != nil {
		return x.MsgRandom
	}
	return 0
}

func (x *SendC2CMessageReq) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *SendC2CMessageReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendC2CMessageReq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *SendC2CMessageReq) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

// 发送C2C消息响应
type SendC2CMessageRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendC2CMessageRsp) Reset() {
	*x = SendC2CMessageRsp{}
	mi := &file_proto_biz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendC2CMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendC2CMessageRsp) ProtoMessage() {}

func (x *SendC2CMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendC2CMessageRsp.ProtoReflect.Descriptor instead.
func (*SendC2CMessageRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{6}
}

func (x *SendC2CMessageRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendC2CMessageRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送群消息请求，用于向群发送消息
type SendGroupMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`             // 消息ID
	GroupCode     string                 `protobuf:"bytes,2,opt,name=groupCode,proto3" json:"groupCode,omitempty"`     // 群号
	FromAccount   string                 `protobuf:"bytes,3,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"` // 发送者账号
	ToAccount     string                 `protobuf:"bytes,4,opt,name=toAccount,proto3" json:"toAccount,omitempty"`     // 接收者账号（@成员时使用）
	Random        string                 `protobuf:"bytes,5,opt,name=random,proto3" json:"random,omitempty"`           // 随机数
	MsgBody       []*MsgBodyElement      `protobuf:"bytes,6,rep,name=msgBody,proto3" json:"msgBody,omitempty"`         // 消息体列表
	RefMsgId      string                 `protobuf:"bytes,7,opt,name=refMsgId,proto3" json:"refMsgId,omitempty"`       // 引用消息ID
	MsgSeq        uint64                 `protobuf:"varint,8,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`          // 消息序列号
	LogExt        *LogInfoExt            `protobuf:"bytes,9,opt,name=logExt,proto3" json:"logExt,omitempty"`           // 日志扩展信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageReq) Reset() {
	*x = SendGroupMessageReq{}
	mi := &file_proto_biz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageReq) ProtoMessage() {}

func (x *SendGroupMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageReq.ProtoReflect.Descriptor instead.
func (*SendGroupMessageReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{7}
}

func (x *SendGroupMessageReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendGroupMessageReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendGroupMessageReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendGroupMessageReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendGroupMessageReq) GetRandom() string {
	if x != nil {
		return x.Random
	}
	return ""
}

func (x *SendGroupMessageReq) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *SendGroupMessageReq) GetRefMsgId() string {
	if x != nil {
		return x.RefMsgId
	}
	return ""
}

func (x *SendGroupMessageReq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *SendGroupMessageReq) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

// 发送群消息响应
type SendGroupMessageRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageRsp) Reset() {
	*x = SendGroupMessageRsp{}
	mi := &file_proto_biz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageRsp) ProtoMessage() {}

func (x *SendGroupMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageRsp.ProtoReflect.Descriptor instead.
func (*SendGroupMessageRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{8}
}

func (x *SendGroupMessageRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupMessageRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 进站消息推送结构
type InboundMessagePush struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CallbackCommand      string                 `protobuf:"bytes,1,opt,name=callbackCommand,proto3" json:"callbackCommand,omitempty"`                            // 回调命令
	FromAccount          string                 `protobuf:"bytes,2,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`                                    // 发送者账号
	ToAccount            string                 `protobuf:"bytes,3,opt,name=toAccount,proto3" json:"toAccount,omitempty"`                                        // 接收者账号
	SenderNickname       string                 `protobuf:"bytes,4,opt,name=senderNickname,proto3" json:"senderNickname,omitempty"`                              // 发送者昵称
	GroupId              string                 `protobuf:"bytes,5,opt,name=groupId,proto3" json:"groupId,omitempty"`                                            // 群ID
	GroupCode            string                 `protobuf:"bytes,6,opt,name=groupCode,proto3" json:"groupCode,omitempty"`                                        // 群号
	GroupName            string                 `protobuf:"bytes,7,opt,name=groupName,proto3" json:"groupName,omitempty"`                                        // 群名称
	MsgSeq               uint32                 `protobuf:"varint,8,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`                                             // 消息序列号
	MsgRandom            uint32                 `protobuf:"varint,9,opt,name=msgRandom,proto3" json:"msgRandom,omitempty"`                                       // 消息随机数
	MsgTime              uint32                 `protobuf:"varint,10,opt,name=msgTime,proto3" json:"msgTime,omitempty"`                                          // 消息时间
	MsgKey               string                 `protobuf:"bytes,11,opt,name=msgKey,proto3" json:"msgKey,omitempty"`                                             // 消息Key
	MsgId                string                 `protobuf:"bytes,12,opt,name=msgId,proto3" json:"msgId,omitempty"`                                               // 消息ID
	MsgBody              []*MsgBodyElement      `protobuf:"bytes,13,rep,name=msgBody,proto3" json:"msgBody,omitempty"`                                           // 消息体列表
	CloudCustomData      string                 `protobuf:"bytes,14,opt,name=cloudCustomData,proto3" json:"cloudCustomData,omitempty"`                           // 云端自定义数据
	EventTime            uint32                 `protobuf:"varint,15,opt,name=eventTime,proto3" json:"eventTime,omitempty"`                                      // 事件时间
	BotOwnerId           string                 `protobuf:"bytes,16,opt,name=botOwnerId,proto3" json:"botOwnerId,omitempty"`                                     // Bot拥有者ID
	RecallMsgSeqList     []*ImMsgSeq            `protobuf:"bytes,17,rep,name=recallMsgSeqList,proto3" json:"recallMsgSeqList,omitempty"`                         // 撤回消息序列号列表
	ClawMsgType          EnumCLawMsgType        `protobuf:"varint,18,opt,name=clawMsgType,proto3,enum=yuanbao_biz.EnumCLawMsgType" json:"clawMsgType,omitempty"` // 消息类型（群/私）
	PrivateFromGroupCode string                 `protobuf:"bytes,19,opt,name=privateFromGroupCode,proto3" json:"privateFromGroupCode,omitempty"`                 // 私聊来源群号
	LogExt               *LogInfoExt            `protobuf:"bytes,20,opt,name=logExt,proto3" json:"logExt,omitempty"`                                             // 日志扩展信息
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InboundMessagePush) Reset() {
	*x = InboundMessagePush{}
	mi := &file_proto_biz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessagePush) ProtoMessage() {}

func (x *InboundMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessagePush.ProtoReflect.Descriptor instead.
func (*InboundMessagePush) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{9}
}

func (x *InboundMessagePush) GetCallbackCommand() string {
	if x != nil {
		return x.CallbackCommand
	}
	return ""
}

func (x *InboundMessagePush) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *InboundMessagePush) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *InboundMessagePush) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *InboundMessagePush) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *InboundMessagePush) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *InboundMessagePush) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *InboundMessagePush) GetMsgSeq() uint32 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *InboundMessagePush) GetMsgRandom() uint32 {
	if x != nil {
		return x.MsgRandom
	}
	return 0
}

func (x *InboundMessagePush) GetMsgTime() uint32 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *InboundMessagePush) GetMsgKey() string {
	if x != nil {
		return x.MsgKey
	}
	return ""
}

func (x *InboundMessagePush) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *InboundMessagePush) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *InboundMessagePush) GetCloudCustomData() string {
	if x != nil {
		return x.CloudCustomData
	}
	return ""
}

func (x *InboundMessagePush) GetEventTime() uint32 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *InboundMessagePush) GetBotOwnerId() string {
	if x != nil {
		return x.BotOwnerId
	}
	return ""
}

func (x *InboundMessagePush) GetRecallMsgSeqList() []*ImMsgSeq {
	if x != nil {
		return x.RecallMsgSeqList
	}
	return nil
}

func (x *InboundMessagePush) GetClawMsgType() EnumCLawMsgType {
	if x != nil {
		return x.ClawMsgType
	}
	return EnumCLawMsgType_CLAW_MSG_UNKNOWN
}

func (x *InboundMessagePush) GetPrivateFromGroupCode() string {
	if x != nil {
		return x.PrivateFromGroupCode
	}
	return ""
}

func (x *InboundMessagePush) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

// 获取群成员列表请求
type GetGroupMemberListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupCode     string                 `protobuf:"bytes,1,opt,name=groupCode,proto3" json:"groupCode,omitempty"` // 群号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListReq) Reset() {
	*x = GetGroupMemberListReq{}
	mi := &file_proto_biz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListReq) ProtoMessage() {}

func (x *GetGroupMemberListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListReq.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupMemberListReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

// 获取群成员列表响应
type GetGroupMemberListRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`            // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`       // 错误信息
	MemberList    []*Member              `protobuf:"bytes,3,rep,name=memberList,proto3" json:"memberList,omitempty"` // 成员列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListRsp) Reset() {
	*x = GetGroupMemberListRsp{}
	mi := &file_proto_biz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListRsp) ProtoMessage() {}

func (x *GetGroupMemberListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListRsp.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{11}
}

func (x *GetGroupMemberListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGroupMemberListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupMemberListRsp) GetMemberList() []*Member {
	if x != nil {
		return x.MemberList
	}
	return nil
}

// 群成员信息
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`      // 用户ID
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`  // 昵称
	UserType      int32                  `protobuf:"varint,3,opt,name=userType,proto3" json:"userType,omitempty"` // 用户类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_biz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{12}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Member) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

// 查询群信息请求
type QueryGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupCode     string                 `protobuf:"bytes,1,opt,name=groupCode,proto3" json:"groupCode,omitempty"` // 群号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupInfoReq) Reset() {
	*x = QueryGroupInfoReq{}
	mi := &file_proto_biz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInfoReq) ProtoMessage() {}

func (x *QueryGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInfoReq.ProtoReflect.Descriptor instead.
func (*QueryGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{13}
}

func (x *QueryGroupInfoReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

// 查询群信息响应
type QueryGroupInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`          // 错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`             // 错误信息
	GroupInfo     *GroupInfo             `protobuf:"bytes,3,opt,name=groupInfo,proto3" json:"groupInfo,omitempty"` // 群信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupInfoRsp) Reset() {
	*x = QueryGroupInfoRsp{}
	mi := &file_proto_biz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInfoRsp) ProtoMessage() {}

func (x *QueryGroupInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryGroupInfoRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{14}
}

func (x *QueryGroupInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryGroupInfoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryGroupInfoRsp) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

// 群信息
type GroupInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GroupName          string                 `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`                   // 群名称
	GroupOwnerUserId   string                 `protobuf:"bytes,2,opt,name=groupOwnerUserId,proto3" json:"groupOwnerUserId,omitempty"`     // 群主用户ID
	GroupOwnerNickname string                 `protobuf:"bytes,3,opt,name=groupOwnerNickname,proto3" json:"groupOwnerNickname,omitempty"` // 群主昵称
	GroupSize          int32                  `protobuf:"varint,4,opt,name=groupSize,proto3" json:"groupSize,omitempty"`                  // 群成员数量
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_biz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{15}
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetGroupOwnerUserId() string {
	if x != nil {
		return x.GroupOwnerUserId
	}
	return ""
}

func (x *GroupInfo) GetGroupOwnerNickname() string {
	if x != nil {
		return x.GroupOwnerNickname
	}
	return ""
}

func (x *GroupInfo) GetGroupSize() int32 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

// 发送私聊心跳请求，用于私聊场景下的心跳检测
type SendPrivateHeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`                             // 发送者账号
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`                                 // 接收者账号
	Heartbeat     EnumHeartbeat          `protobuf:"varint,3,opt,name=heartbeat,proto3,enum=yuanbao_biz.EnumHeartbeat" json:"heartbeat,omitempty"` // 心跳状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateHeartbeatReq) Reset() {
	*x = SendPrivateHeartbeatReq{}
	mi := &file_proto_biz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateHeartbeatReq) ProtoMessage() {}

func (x *SendPrivateHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateHeartbeatReq.ProtoReflect.Descriptor instead.
func (*SendPrivateHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{16}
}

func (x *SendPrivateHeartbeatReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendPrivateHeartbeatReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendPrivateHeartbeatReq) GetHeartbeat() EnumHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return EnumHeartbeat_HEARTBEAT_UNKNOWN
}

// 发送私聊心跳响应
type SendPrivateHeartbeatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateHeartbeatRsp) Reset() {
	*x = SendPrivateHeartbeatRsp{}
	mi := &file_proto_biz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateHeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateHeartbeatRsp) ProtoMessage() {}

func (x *SendPrivateHeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateHeartbeatRsp.ProtoReflect.Descriptor instead.
func (*SendPrivateHeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{17}
}

func (x *SendPrivateHeartbeatRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendPrivateHeartbeatRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 发送群心跳请求，用于群聊场景下的心跳检测
type SendGroupHeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`                             // 发送者账号
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`                                 // 接收者账号
	GroupCode     string                 `protobuf:"bytes,3,opt,name=groupCode,proto3" json:"groupCode,omitempty"`                                 // 群号
	SendTime      int64                  `protobuf:"varint,4,opt,name=sendTime,proto3" json:"sendTime,omitempty"`                                  // 发送时间
	Heartbeat     EnumHeartbeat          `protobuf:"varint,5,opt,name=heartbeat,proto3,enum=yuanbao_biz.EnumHeartbeat" json:"heartbeat,omitempty"` // 心跳状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupHeartbeatReq) Reset() {
	*x = SendGroupHeartbeatReq{}
	mi := &file_proto_biz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupHeartbeatReq) ProtoMessage() {}

func (x *SendGroupHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupHeartbeatReq.ProtoReflect.Descriptor instead.
func (*SendGroupHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{18}
}

func (x *SendGroupHeartbeatReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendGroupHeartbeatReq) GetHeartbeat() EnumHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return EnumHeartbeat_HEARTBEAT_UNKNOWN
}

// 发送群心跳响应
type SendGroupHeartbeatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupHeartbeatRsp) Reset() {
	*x = SendGroupHeartbeatRsp{}
	mi := &file_proto_biz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupHeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupHeartbeatRsp) ProtoMessage() {}

func (x *SendGroupHeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupHeartbeatRsp.ProtoReflect.Descriptor instead.
func (*SendGroupHeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_proto_biz_proto_rawDescGZIP(), []int{19}
}

func (x *SendGroupHeartbeatRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupHeartbeatRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_biz_proto protoreflect.FileDescriptor

const file_proto_biz_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/biz.proto\x12\vyuanbao_biz\"8\n" +
	"\bImMsgSeq\x12\x16\n" +
	"\x06msgSeq\x18\x01 \x01(\x04R\x06msgSeq\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\tR\x05msgId\"z\n" +
	"\x10ImImageInfoArray\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xcd\x02\n" +
	"\n" +
	"MsgContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12 \n" +
	"\vimageFormat\x18\x03 \x01(\rR\vimageFormat\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x12\x14\n" +
	"\x05sound\x18\a \x01(\tR\x05sound\x12E\n" +
	"\x0eimageInfoArray\x18\b \x03(\v2\x1d.yuanbao_biz.ImImageInfoArrayR\x0eimageInfoArray\x12\x14\n" +
	"\x05index\x18\t \x01(\rR\x05index\x12\x10\n" +
	"\x03url\x18\n" +
	" \x01(\tR\x03url\x12\x1a\n" +
	"\bfileSize\x18\v \x01(\rR\bfileSize\x12\x1a\n" +
	"\bfileName\x18\f \x01(\tR\bfileName\"c\n" +
	"\x0eMsgBodyElement\x12\x18\n" +
	"\amsgType\x18\x01 \x01(\tR\amsgType\x127\n" +
	"\n" +
	"msgContent\x18\x02 \x01(\v2\x17.yuanbao_biz.MsgContentR\n" +
	"msgContent\"&\n" +
	"\n" +
	"LogInfoExt\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\"\xa5\x02\n" +
	"\x11SendC2CMessageReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x12 \n" +
	"\vfromAccount\x18\x03 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\tmsgRandom\x18\x04 \x01(\rR\tmsgRandom\x125\n" +
	"\amsgBody\x18\x05 \x03(\v2\x1b.yuanbao_biz.MsgBodyElementR\amsgBody\x12\x1c\n" +
	"\tgroupCode\x18\x06 \x01(\tR\tgroupCode\x12\x16\n" +
	"\x06msgSeq\x18\a \x01(\x04R\x06msgSeq\x12/\n" +
	"\x06logExt\x18\b \x01(\v2\x17.yuanbao_biz.LogInfoExtR\x06logExt\"A\n" +
	"\x11SendC2CMessageRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbd\x02\n" +
	"\x13SendGroupMessageReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\tgroupCode\x18\x02 \x01(\tR\tgroupCode\x12 \n" +
	"\vfromAccount\x18\x03 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x04 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06random\x18\x05 \x01(\tR\x06random\x125\n" +
	"\amsgBody\x18\x06 \x03(\v2\x1b.yuanbao_biz.MsgBodyElementR\amsgBody\x12\x1a\n" +
	"\brefMsgId\x18\a \x01(\tR\brefMsgId\x12\x16\n" +
	"\x06msgSeq\x18\b \x01(\x04R\x06msgSeq\x12/\n" +
	"\x06logExt\x18\t \x01(\v2\x17.yuanbao_biz.LogInfoExtR\x06logExt\"C\n" +
	"\x13SendGroupMessageRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x06\n" +
	"\x12InboundMessagePush\x12(\n" +
	"\x0fcallbackCommand\x18\x01 \x01(\tR\x0fcallbackCommand\x12 \n" +
	"\vfromAccount\x18\x02 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x03 \x01(\tR\ttoAccount\x12&\n" +
	"\x0esenderNickname\x18\x04 \x01(\tR\x0esenderNickname\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\tR\agroupId\x12\x1c\n" +
	"\tgroupCode\x18\x06 \x01(\tR\tgroupCode\x12\x1c\n" +
	"\tgroupName\x18\a \x01(\tR\tgroupName\x12\x16\n" +
	"\x06msgSeq\x18\b \x01(\rR\x06msgSeq\x12\x1c\n" +
	"\tmsgRandom\x18\t \x01(\rR\tmsgRandom\x12\x18\n" +
	"\amsgTime\x18\n" +
	" \x01(\rR\amsgTime\x12\x16\n" +
	"\x06msgKey\x18\v \x01(\tR\x06msgKey\x12\x14\n" +
	"\x05msgId\x18\f \x01(\tR\x05msgId\x125\n" +
	"\amsgBody\x18\r \x03(\v2\x1b.yuanbao_biz.MsgBodyElementR\amsgBody\x12(\n" +
	"\x0fcloudCustomData\x18\x0e \x01(\tR\x0fcloudCustomData\x12\x1c\n" +
	"\teventTime\x18\x0f \x01(\rR\teventTime\x12\x1e\n" +
	"\n" +
	"botOwnerId\x18\x10 \x01(\tR\n" +
	"botOwnerId\x12A\n" +
	"\x10recallMsgSeqList\x18\x11 \x03(\v2\x15.yuanbao_biz.ImMsgSeqR\x10recallMsgSeqList\x12>\n" +
	"\vclawMsgType\x18\x12 \x01(\x0e2\x1c.yuanbao_biz.EnumCLawMsgTypeR\vclawMsgType\x122\n" +
	"\x14privateFromGroupCode\x18\x13 \x01(\tR\x14privateFromGroupCode\x12/\n" +
	"\x06logExt\x18\x14 \x01(\v2\x17.yuanbao_biz.LogInfoExtR\x06logExt\"5\n" +
	"\x15GetGroupMemberListReq\x12\x1c\n" +
	"\tgroupCode\x18\x01 \x01(\tR\tgroupCode\"z\n" +
	"\x15GetGroupMemberListRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\n" +
	"memberList\x18\x03 \x03(\v2\x13.yuanbao_biz.MemberR\n" +
	"memberList\"X\n" +
	"\x06Member\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1a\n" +
	"\buserType\x18\x03 \x01(\x05R\buserType\"1\n" +
	"\x11QueryGroupInfoReq\x12\x1c\n" +
	"\tgroupCode\x18\x01 \x01(\tR\tgroupCode\"o\n" +
	"\x11QueryGroupInfoRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x124\n" +
	"\tgroupInfo\x18\x03 \x01(\v2\x16.yuanbao_biz.GroupInfoR\tgroupInfo\"\xa3\x01\n" +
	"\tGroupInfo\x12\x1c\n" +
	"\tgroupName\x18\x01 \x01(\tR\tgroupName\x12*\n" +
	"\x10groupOwnerUserId\x18\x02 \x01(\tR\x10groupOwnerUserId\x12.\n" +
	"\x12groupOwnerNickname\x18\x03 \x01(\tR\x12groupOwnerNickname\x12\x1c\n" +
	"\tgroupSize\x18\x04 \x01(\x05R\tgroupSize\"\x93\x01\n" +
	"\x17SendPrivateHeartbeatReq\x12 \n" +
	"\vfromAccount\x18\x01 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x128\n" +
	"\theartbeat\x18\x03 \x01(\x0e2\x1a.yuanbao_biz.EnumHeartbeatR\theartbeat\"?\n" +
	"\x17SendPrivateHeartbeatRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xcb\x01\n" +
	"\x15SendGroupHeartbeatReq\x12 \n" +
	"\vfromAccount\x18\x01 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x12\x1c\n" +
	"\tgroupCode\x18\x03 \x01(\tR\tgroupCode\x12\x1a\n" +
	"\bsendTime\x18\x04 \x01(\x03R\bsendTime\x128\n" +
	"\theartbeat\x18\x05 \x01(\x0e2\x1a.yuanbao_biz.EnumHeartbeatR\theartbeat\"=\n" +
	"\x15SendGroupHeartbeatRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*Q\n" +
	"\x0fEnumCLawMsgType\x12\x14\n" +
	"\x10CLAW_MSG_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eCLAW_MSG_GROUP\x10\x01\x12\x14\n" +
	"\x10CLAW_MSG_PRIVATE\x10\x02*S\n" +
	"\rEnumHeartbeat\x12\x15\n" +
	"\x11HEARTBEAT_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11HEARTBEAT_RUNNING\x10\x01\x12\x14\n" +
	"\x10HEARTBEAT_FINISH\x10\x02B\x18Z\x16yuanbao-go/wsproto/bizb\x06proto3"

var (
	file_proto_biz_proto_rawDescOnce sync.Once
	file_proto_biz_proto_rawDescData []byte
)

func file_proto_biz_proto_rawDescGZIP() []byte {
	file_proto_biz_proto_rawDescOnce.Do(func() {
		file_proto_biz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_biz_proto_rawDesc), len(file_proto_biz_proto_rawDesc)))
	})
	return file_proto_biz_proto_rawDescData
}

var file_proto_biz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_biz_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_biz_proto_goTypes = []any{
	(EnumCLawMsgType)(0),            // 0: yuanbao_biz.EnumCLawMsgType
	(EnumHeartbeat)(0),              // 1: yuanbao_biz.EnumHeartbeat
	(*ImMsgSeq)(nil),                // 2: yuanbao_biz.ImMsgSeq
	(*ImImageInfoArray)(nil),        // 3: yuanbao_biz.ImImageInfoArray
	(*MsgContent)(nil),              // 4: yuanbao_biz.MsgContent
	(*MsgBodyElement)(nil),          // 5: yuanbao_biz.MsgBodyElement
	(*LogInfoExt)(nil),              // 6: yuanbao_biz.LogInfoExt
	(*SendC2CMessageReq)(nil),       // 7: yuanbao_biz.SendC2CMessageReq
	(*SendC2CMessageRsp)(nil),       // 8: yuanbao_biz.SendC2CMessageRsp
	(*SendGroupMessageReq)(nil),     // 9: yuanbao_biz.SendGroupMessageReq
	(*SendGroupMessageRsp)(nil),     // 10: yuanbao_biz.SendGroupMessageRsp
	(*InboundMessagePush)(nil),      // 11: yuanbao_biz.InboundMessagePush
	(*GetGroupMemberListReq)(nil),   // 12: yuanbao_biz.GetGroupMemberListReq
	(*GetGroupMemberListRsp)(nil),   // 13: yuanbao_biz.GetGroupMemberListRsp
	(*Member)(nil),                  // 14: yuanbao_biz.Member
	(*QueryGroupInfoReq)(nil),       // 15: yuanbao_biz.QueryGroupInfoReq
	(*QueryGroupInfoRsp)(nil),       // 16: yuanbao_biz.QueryGroupInfoRsp
	(*GroupInfo)(nil),               // 17: yuanbao_biz.GroupInfo
	(*SendPrivateHeartbeatReq)(nil), // 18: yuanbao_biz.SendPrivateHeartbeatReq
	(*SendPrivateHeartbeatRsp)(nil), // 19: yuanbao_biz.SendPrivateHeartbeatRsp
	(*SendGroupHeartbeatReq)(nil),   // 20: yuanbao_biz.SendGroupHeartbeatReq
	(*SendGroupHeartbeatRsp)(nil),   // 21: yuanbao_biz.SendGroupHeartbeatRsp
}
var file_proto_biz_proto_depIdxs = []int32{
	3,  // 0: yuanbao_biz.MsgContent.imageInfoArray:type_name -> yuanbao_biz.ImImageInfoArray
	4,  // 1: yuanbao_biz.MsgBodyElement.msgContent:type_name -> yuanbao_biz.MsgContent
	5,  // 2: yuanbao_biz.SendC2CMessageReq.msgBody:type_name -> yuanbao_biz.MsgBodyElement
	6,  // 3: yuanbao_biz.SendC2CMessageReq.logExt:type_name -> yuanbao_biz.LogInfoExt
	5,  // 4: yuanbao_biz.SendGroupMessageReq.msgBody:type_name -> yuanbao_biz.MsgBodyElement
	6,  // 5: yuanbao_biz.SendGroupMessageReq.logExt:type_name -> yuanbao_biz.LogInfoExt
	5,  // 6: yuanbao_biz.InboundMessagePush.msgBody:type_name -> yuanbao_biz.MsgBodyElement
	2,  // 7: yuanbao_biz.InboundMessagePush.recallMsgSeqList:type_name -> yuanbao_biz.ImMsgSeq
	0,  // 8: yuanbao_biz.InboundMessagePush.clawMsgType:type_name -> yuanbao_biz.EnumCLawMsgType
	6,  // 9: yuanbao_biz.InboundMessagePush.logExt:type_name -> yuanbao_biz.LogInfoExt
	14, // 10: yuanbao_biz.GetGroupMemberListRsp.memberList:type_name -> yuanbao_biz.Member
	17, // 11: yuanbao_biz.QueryGroupInfoRsp.groupInfo:type_name -> yuanbao_biz.GroupInfo
	1,  // 12: yuanbao_biz.SendPrivateHeartbeatReq.heartbeat:type_name -> yuanbao_biz.EnumHeartbeat
	1,  // 13: yuanbao_biz.SendGroupHeartbeatReq.heartbeat:type_name -> yuanbao_biz.EnumHeartbeat
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_biz_proto_init() }
func file_proto_biz_proto_init() {
	if File_proto_biz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_biz_proto_rawDesc), len(file_proto_biz_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_biz_proto_goTypes,
		DependencyIndexes: file_proto_biz_proto_depIdxs,
		EnumInfos:         file_proto_biz_proto_enumTypes,
		MessageInfos:      file_proto_biz_proto_msgTypes,
	}.Build()
	File_proto_biz_proto = out.File
	file_proto_biz_proto_goTypes = nil
	file_proto_biz_proto_depIdxs = nil
}
