// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/conn.proto

// 对应 Conn 连接层协议

package conn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码枚举
type RetCode int32

const (
	RetCode_SUCCESS                      RetCode = 0  // 成功
	RetCode_PARAMS_INVALID               RetCode = 1  // 参数无效
	RetCode_AUTH_FAIL                    RetCode = 2  // 认证失败
	RetCode_UNKNOWN_ROUTE                RetCode = 3  // 未知路由
	RetCode_ALREADY_AUTH                 RetCode = 4  // 已认证
	RetCode_SAME_KIND_DEV_LOGIN          RetCode = 5  // 同类型设备已登录
	RetCode_AUTH_TOKEN_INVALID           RetCode = 6  // 认证令牌无效
	RetCode_AUTH_TOKEN_EXPIRED           RetCode = 7  // 认证令牌已过期
	RetCode_AUTH_USER_NOT_REGISTERED     RetCode = 8  // 用户未注册
	RetCode_AUTH_USER_FORBIDDEN          RetCode = 9  // 用户被禁用
	RetCode_AUTH_USER_UNQUALIFIED        RetCode = 10 // 用户不合格
	RetCode_AUTH_TOKEN_FORCED_EXPIRATION RetCode = 11 // 令牌被强制过期
	RetCode_PROHIBIT_APP_VERSION         RetCode = 12 // 禁止的App版本
	RetCode_PACKAGE_SIGN_ILLEGAL         RetCode = 13 // 包签名非法
	RetCode_INNER_SVR_FAIL               RetCode = 14 // 内部服务错误
	RetCode_OVERLOAD_CONTROL             RetCode = 15 // 过载控制
	RetCode_SET_STATE_CONFLICT           RetCode = 16 // 状态设置冲突
	RetCode_CONN_OVER_LIMIT              RetCode = 17 // 连接数超限
	RetCode_NO_USER_ONLINE               RetCode = 18 // 用户不在线
	RetCode_PARTIAL_FAIL                 RetCode = 19 // 部分失败
	RetCode_NET_FAIL                     RetCode = 20 // 网络错误
	RetCode_BACKEND_RETURN_FAIL          RetCode = 21 // 后端返回失败
	RetCode_USER_OFFLINE                 RetCode = 22 // 用户离线
	RetCode_USER_NOT_EXIST               RetCode = 23 // 用户不存在
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:  "SUCCESS",
		1:  "PARAMS_INVALID",
		2:  "AUTH_FAIL",
		3:  "UNKNOWN_ROUTE",
		4:  "ALREADY_AUTH",
		5:  "SAME_KIND_DEV_LOGIN",
		6:  "AUTH_TOKEN_INVALID",
		7:  "AUTH_TOKEN_EXPIRED",
		8:  "AUTH_USER_NOT_REGISTERED",
		9:  "AUTH_USER_FORBIDDEN",
		10: "AUTH_USER_UNQUALIFIED",
		11: "AUTH_TOKEN_FORCED_EXPIRATION",
		12: "PROHIBIT_APP_VERSION",
		13: "PACKAGE_SIGN_ILLEGAL",
		14: "INNER_SVR_FAIL",
		15: "OVERLOAD_CONTROL",
		16: "SET_STATE_CONFLICT",
		17: "CONN_OVER_LIMIT",
		18: "NO_USER_ONLINE",
		19: "PARTIAL_FAIL",
		20: "NET_FAIL",
		21: "BACKEND_RETURN_FAIL",
		22: "USER_OFFLINE",
		23: "USER_NOT_EXIST",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":                      0,
		"PARAMS_INVALID":               1,
		"AUTH_FAIL":                    2,
		"UNKNOWN_ROUTE":                3,
		"ALREADY_AUTH":                 4,
		"SAME_KIND_DEV_LOGIN":          5,
		"AUTH_TOKEN_INVALID":           6,
		"AUTH_TOKEN_EXPIRED":           7,
		"AUTH_USER_NOT_REGISTERED":     8,
		"AUTH_USER_FORBIDDEN":          9,
		"AUTH_USER_UNQUALIFIED":        10,
		"AUTH_TOKEN_FORCED_EXPIRATION": 11,
		"PROHIBIT_APP_VERSION":         12,
		"PACKAGE_SIGN_ILLEGAL":         13,
		"INNER_SVR_FAIL":               14,
		"OVERLOAD_CONTROL":             15,
		"SET_STATE_CONFLICT":           16,
		"CONN_OVER_LIMIT":              17,
		"NO_USER_ONLINE":               18,
		"PARTIAL_FAIL":                 19,
		"NET_FAIL":                     20,
		"BACKEND_RETURN_FAIL":          21,
		"USER_OFFLINE":                 22,
		"USER_NOT_EXIST":               23,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_conn_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_proto_conn_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{0}
}

// 元数据键值对，用于传递额外信息
type HeadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 元数据键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 元数据值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadMeta) Reset() {
	*x = HeadMeta{}
	mi := &file_proto_conn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadMeta) ProtoMessage() {}

func (x *HeadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadMeta.ProtoReflect.Descriptor instead.
func (*HeadMeta) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{0}
}

func (x *HeadMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeadMeta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 消息头，包含消息的控制信息和元数据
type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdType       uint32                 `protobuf:"varint,1,opt,name=cmdType,proto3" json:"cmdType,omitempty"` // 命令类型
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`          // 命令名称
	SeqNo         uint32                 `protobuf:"varint,3,opt,name=seqNo,proto3" json:"seqNo,omitempty"`     // 序列号，用于请求响应配对
	MsgId         string                 `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`      // 消息唯一ID
	Module        string                 `protobuf:"bytes,5,opt,name=module,proto3" json:"module,omitempty"`    // 模块名称
	NeedAck       bool                   `protobuf:"varint,6,opt,name=needAck,proto3" json:"needAck,omitempty"` // 是否需要ack确认
	Meta          []*HeadMeta            `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty"`        // 扩展元数据列表
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`   // 响应状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_proto_conn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{1}
}

func (x *Head) GetCmdType() uint32 {
	if x != nil {
		return x.CmdType
	}
	return 0
}

func (x *Head) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Head) GetSeqNo() uint32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *Head) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Head) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Head) GetNeedAck() bool {
	if x != nil {
		return x.NeedAck
	}
	return false
}

func (x *Head) GetMeta() []*HeadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Head) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 完整的连接消息，包含消息头和消息体
type ConnMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *Head                  `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 消息头
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 消息体二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnMsg) Reset() {
	*x = ConnMsg{}
	mi := &file_proto_conn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMsg) ProtoMessage() {}

func (x *ConnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMsg.ProtoReflect.Descriptor instead.
func (*ConnMsg) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{2}
}

func (x *ConnMsg) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *ConnMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 定向推送消息，用于服务器主动推送消息给客户端
type DirectedPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`      // 推送类型
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 推送内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectedPush) Reset() {
	*x = DirectedPush{}
	mi := &file_proto_conn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectedPush) ProtoMessage() {}

func (x *DirectedPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectedPush.ProtoReflect.Descriptor instead.
func (*DirectedPush) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{3}
}

func (x *DirectedPush) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DirectedPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 认证信息，包含用户身份验证所需的凭证
type AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`       // 用户ID
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // 来源标识
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`   // 认证令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	mi := &file_proto_conn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{4}
}

func (x *AuthInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AuthInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuthInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 设备信息，包含客户端设备和应用的相关信息
type DeviceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppVersion         string                 `protobuf:"bytes,1,opt,name=appVersion,proto3" json:"appVersion,omitempty"`                 // App版本号
	AppOperationSystem string                 `protobuf:"bytes,2,opt,name=appOperationSystem,proto3" json:"appOperationSystem,omitempty"` // 操作系统
	AppBundleId        string                 `protobuf:"bytes,3,opt,name=appBundleId,proto3" json:"appBundleId,omitempty"`               // App Bundle ID
	Qimei              string                 `protobuf:"bytes,4,opt,name=qimei,proto3" json:"qimei,omitempty"`                           // Qimei设备标识
	Qimei36            string                 `protobuf:"bytes,5,opt,name=qimei36,proto3" json:"qimei36,omitempty"`                       // Qimei36设备标识
	H38                string                 `protobuf:"bytes,6,opt,name=h38,proto3" json:"h38,omitempty"`                               // H38设备标识
	Language           string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`                     // 语言设置
	DeviceId           string                 `protobuf:"bytes,8,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                     // 设备ID
	DeviceName         string                 `protobuf:"bytes,9,opt,name=deviceName,proto3" json:"deviceName,omitempty"`                 // 设备名称
	InstanceId         string                 `protobuf:"bytes,10,opt,name=instanceId,proto3" json:"instanceId,omitempty"`                // 实例ID
	Tid                string                 `protobuf:"bytes,11,opt,name=tid,proto3" json:"tid,omitempty"`                              // 终端ID
	Uskey              string                 `protobuf:"bytes,12,opt,name=uskey,proto3" json:"uskey,omitempty"`                          // 用户会话Key
	BusParamsMd5       string                 `protobuf:"bytes,13,opt,name=busParamsMd5,proto3" json:"busParamsMd5,omitempty"`            // 业务参数MD5
	PackageType        string                 `protobuf:"bytes,14,opt,name=packageType,proto3" json:"packageType,omitempty"`              // 包类型
	AppPublishChannel  string                 `protobuf:"bytes,15,opt,name=appPublishChannel,proto3" json:"appPublishChannel,omitempty"`  // App发布渠道
	SignVersion        string                 `protobuf:"bytes,16,opt,name=signVersion,proto3" json:"signVersion,omitempty"`              // 签名版本
	PackageSignature   string                 `protobuf:"bytes,17,opt,name=packageSignature,proto3" json:"packageSignature,omitempty"`    // 包签名
	Brand              string                 `protobuf:"bytes,18,opt,name=brand,proto3" json:"brand,omitempty"`                          // 设备品牌
	H42                string                 `protobuf:"bytes,19,opt,name=h42,proto3" json:"h42,omitempty"`                              // H42设备标识
	XDeviceId          string                 `protobuf:"bytes,20,opt,name=xDeviceId,proto3" json:"xDeviceId,omitempty"`                  // X设备ID
	XPlatform          string                 `protobuf:"bytes,21,opt,name=xPlatform,proto3" json:"xPlatform,omitempty"`                  // X平台标识
	DialToken          string                 `protobuf:"bytes,22,opt,name=dialToken,proto3" json:"dialToken,omitempty"`                  // 拨号Token
	Qimei36Token       string                 `protobuf:"bytes,23,opt,name=qimei36Token,proto3" json:"qimei36Token,omitempty"`            // Qimei36 Token
	BotVersion         string                 `protobuf:"bytes,24,opt,name=botVersion,proto3" json:"botVersion,omitempty"`                // Bot版本
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_conn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetAppOperationSystem() string {
	if x != nil {
		return x.AppOperationSystem
	}
	return ""
}

func (x *DeviceInfo) GetAppBundleId() string {
	if x != nil {
		return x.AppBundleId
	}
	return ""
}

func (x *DeviceInfo) GetQimei() string {
	if x != nil {
		return x.Qimei
	}
	return ""
}

func (x *DeviceInfo) GetQimei36() string {
	if x != nil {
		return x.Qimei36
	}
	return ""
}

func (x *DeviceInfo) GetH38() string {
	if x != nil {
		return x.H38
	}
	return ""
}

func (x *DeviceInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeviceInfo) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *DeviceInfo) GetUskey() string {
	if x != nil {
		return x.Uskey
	}
	return ""
}

func (x *DeviceInfo) GetBusParamsMd5() string {
	if x != nil {
		return x.BusParamsMd5
	}
	return ""
}

func (x *DeviceInfo) GetPackageType() string {
	if x != nil {
		return x.PackageType
	}
	return ""
}

func (x *DeviceInfo) GetAppPublishChannel() string {
	if x != nil {
		return x.AppPublishChannel
	}
	return ""
}

func (x *DeviceInfo) GetSignVersion() string {
	if x != nil {
		return x.SignVersion
	}
	return ""
}

func (x *DeviceInfo) GetPackageSignature() string {
	if x != nil {
		return x.PackageSignature
	}
	return ""
}

func (x *DeviceInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceInfo) GetH42() string {
	if x != nil {
		return x.H42
	}
	return ""
}

func (x *DeviceInfo) GetXDeviceId() string {
	if x != nil {
		return x.XDeviceId
	}
	return ""
}

func (x *DeviceInfo) GetXPlatform() string {
	if x != nil {
		return x.XPlatform
	}
	return ""
}

func (x *DeviceInfo) GetDialToken() string {
	if x != nil {
		return x.DialToken
	}
	return ""
}

func (x *DeviceInfo) GetQimei36Token() string {
	if x != nil {
		return x.Qimei36Token
	}
	return ""
}

func (x *DeviceInfo) GetBotVersion() string {
	if x != nil {
		return x.BotVersion
	}
	return ""
}

// 容器信息，用于标识客户端容器类型
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`          // 容器类型
	UniqueKey     string                 `protobuf:"bytes,2,opt,name=uniqueKey,proto3" json:"uniqueKey,omitempty"` // 唯一键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_conn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Container) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

// 认证绑定请求，客户端发起认证绑定的请求
type AuthBindReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`                 // 业务ID
	AuthInfo      *AuthInfo              `protobuf:"bytes,2,opt,name=authInfo,proto3" json:"authInfo,omitempty"`           // 认证信息
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,3,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`       // 设备信息
	ContainerInfo *Container             `protobuf:"bytes,4,opt,name=containerInfo,proto3" json:"containerInfo,omitempty"` // 容器信息
	EnvName       string                 `protobuf:"bytes,5,opt,name=envName,proto3" json:"envName,omitempty"`             // 环境名称
	BindMode      uint32                 `protobuf:"varint,6,opt,name=bindMode,proto3" json:"bindMode,omitempty"`          // 绑定模式
	ForceToken    string                 `protobuf:"bytes,7,opt,name=forceToken,proto3" json:"forceToken,omitempty"`       // 强制令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthBindReq) Reset() {
	*x = AuthBindReq{}
	mi := &file_proto_conn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindReq) ProtoMessage() {}

func (x *AuthBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindReq.ProtoReflect.Descriptor instead.
func (*AuthBindReq) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{7}
}

func (x *AuthBindReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AuthBindReq) GetAuthInfo() *AuthInfo {
	if x != nil {
		return x.AuthInfo
	}
	return nil
}

func (x *AuthBindReq) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *AuthBindReq) GetContainerInfo() *Container {
	if x != nil {
		return x.ContainerInfo
	}
	return nil
}

func (x *AuthBindReq) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *AuthBindReq) GetBindMode() uint32 {
	if x != nil {
		return x.BindMode
	}
	return 0
}

func (x *AuthBindReq) GetForceToken() string {
	if x != nil {
		return x.ForceToken
	}
	return ""
}

// 认证绑定响应，服务器返回认证绑定结果
type AuthBindRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`           // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // 错误信息
	ConnectId     string                 `protobuf:"bytes,3,opt,name=connectId,proto3" json:"connectId,omitempty"`  // 连接ID
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	ClientIp      string                 `protobuf:"bytes,5,opt,name=clientIp,proto3" json:"clientIp,omitempty"`    // 客户端IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthBindRsp) Reset() {
	*x = AuthBindRsp{}
	mi := &file_proto_conn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindRsp) ProtoMessage() {}

func (x *AuthBindRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindRsp.ProtoReflect.Descriptor instead.
func (*AuthBindRsp) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{8}
}

func (x *AuthBindRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthBindRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthBindRsp) GetConnectId() string {
	if x != nil {
		return x.ConnectId
	}
	return ""
}

func (x *AuthBindRsp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthBindRsp) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 心跳请求，客户端发送心跳保活
type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_proto_conn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{9}
}

// 心跳响应，服务器回复心跳并携带心跳间隔
type PingRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeartInterval uint32                 `protobuf:"varint,1,opt,name=heartInterval,proto3" json:"heartInterval,omitempty"` // 心跳间隔（秒）
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // 服务器时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRsp) Reset() {
	*x = PingRsp{}
	mi := &file_proto_conn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRsp) ProtoMessage() {}

func (x *PingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRsp.ProtoReflect.Descriptor instead.
func (*PingRsp) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{10}
}

func (x *PingRsp) GetHeartInterval() uint32 {
	if x != nil {
		return x.HeartInterval
	}
	return 0
}

func (x *PingRsp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 踢出消息，服务器强制客户端下线
type KickoutMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                  // 状态码
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                   // 踢出原因
	OtherDeviceName string                 `protobuf:"bytes,3,opt,name=otherDeviceName,proto3" json:"otherDeviceName,omitempty"` // 其他设备名称
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KickoutMsg) Reset() {
	*x = KickoutMsg{}
	mi := &file_proto_conn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickoutMsg) ProtoMessage() {}

func (x *KickoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickoutMsg.ProtoReflect.Descriptor instead.
func (*KickoutMsg) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{11}
}

func (x *KickoutMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *KickoutMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickoutMsg) GetOtherDeviceName() string {
	if x != nil {
		return x.OtherDeviceName
	}
	return ""
}

// 元数据键值对
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_proto_conn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{12}
}

func (x *Meta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Meta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 更新元数据请求
type UpdateMetaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetaInfos     []*Meta                `protobuf:"bytes,1,rep,name=metaInfos,proto3" json:"metaInfos,omitempty"` // 元数据信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaReq) Reset() {
	*x = UpdateMetaReq{}
	mi := &file_proto_conn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaReq) ProtoMessage() {}

func (x *UpdateMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaReq.ProtoReflect.Descriptor instead.
func (*UpdateMetaReq) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMetaReq) GetMetaInfos() []*Meta {
	if x != nil {
		return x.MetaInfos
	}
	return nil
}

// 更新元数据响应
type UpdateMetaRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaRsp) Reset() {
	*x = UpdateMetaRsp{}
	mi := &file_proto_conn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaRsp) ProtoMessage() {}

func (x *UpdateMetaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaRsp.ProtoReflect.Descriptor instead.
func (*UpdateMetaRsp) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMetaRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateMetaRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 推送消息，服务器主动推送消息给客户端
type PushMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`       // 命令
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"` // 模块
	MsgId         string                 `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`   // 消息ID
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`     // 消息数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsg) Reset() {
	*x = PushMsg{}
	mi := &file_proto_conn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsg) ProtoMessage() {}

func (x *PushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsg.ProtoReflect.Descriptor instead.
func (*PushMsg) Descriptor() ([]byte, []int) {
	return file_proto_conn_proto_rawDescGZIP(), []int{15}
}

func (x *PushMsg) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *PushMsg) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PushMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PushMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_conn_proto protoreflect.FileDescriptor

const file_proto_conn_proto_rawDesc = "" +
	"\n" +
	"\x10proto/conn.proto\x12\fyuanbao_conn\"2\n" +
	"\bHeadMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd4\x01\n" +
	"\x04Head\x12\x18\n" +
	"\acmdType\x18\x01 \x01(\rR\acmdType\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05seqNo\x18\x03 \x01(\rR\x05seqNo\x12\x14\n" +
	"\x05msgId\x18\x04 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06module\x18\x05 \x01(\tR\x06module\x12\x18\n" +
	"\aneedAck\x18\x06 \x01(\bR\aneedAck\x12*\n" +
	"\x04meta\x18\a \x03(\v2\x16.yuanbao_conn.HeadMetaR\x04meta\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"E\n" +
	"\aConnMsg\x12&\n" +
	"\x04head\x18\x01 \x01(\v2\x12.yuanbao_conn.HeadR\x04head\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"<\n" +
	"\fDirectedPush\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"J\n" +
	"\bAuthInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xe8\x05\n" +
	"\n" +
	"DeviceInfo\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x01 \x01(\tR\n" +
	"appVersion\x12.\n" +
	"\x12appOperationSystem\x18\x02 \x01(\tR\x12appOperationSystem\x12 \n" +
	"\vappBundleId\x18\x03 \x01(\tR\vappBundleId\x12\x14\n" +
	"\x05qimei\x18\x04 \x01(\tR\x05qimei\x12\x18\n" +
	"\aqimei36\x18\x05 \x01(\tR\aqimei36\x12\x10\n" +
	"\x03h38\x18\x06 \x01(\tR\x03h38\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1a\n" +
	"\bdeviceId\x18\b \x01(\tR\bdeviceId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\t \x01(\tR\n" +
	"deviceName\x12\x1e\n" +
	"\n" +
	"instanceId\x18\n" +
	" \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03tid\x18\v \x01(\tR\x03tid\x12\x14\n" +
	"\x05uskey\x18\f \x01(\tR\x05uskey\x12\"\n" +
	"\fbusParamsMd5\x18\r \x01(\tR\fbusParamsMd5\x12 \n" +
	"\vpackageType\x18\x0e \x01(\tR\vpackageType\x12,\n" +
	"\x11appPublishChannel\x18\x0f \x01(\tR\x11appPublishChannel\x12 \n" +
	"\vsignVersion\x18\x10 \x01(\tR\vsignVersion\x12*\n" +
	"\x10packageSignature\x18\x11 \x01(\tR\x10packageSignature\x12\x14\n" +
	"\x05brand\x18\x12 \x01(\tR\x05brand\x12\x10\n" +
	"\x03h42\x18\x13 \x01(\tR\x03h42\x12\x1c\n" +
	"\txDeviceId\x18\x14 \x01(\tR\txDeviceId\x12\x1c\n" +
	"\txPlatform\x18\x15 \x01(\tR\txPlatform\x12\x1c\n" +
	"\tdialToken\x18\x16 \x01(\tR\tdialToken\x12\"\n" +
	"\fqimei36Token\x18\x17 \x01(\tR\fqimei36Token\x12\x1e\n" +
	"\n" +
	"botVersion\x18\x18 \x01(\tR\n" +
	"botVersion\"=\n" +
	"\tContainer\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1c\n" +
	"\tuniqueKey\x18\x02 \x01(\tR\tuniqueKey\"\xa6\x02\n" +
	"\vAuthBindReq\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x122\n" +
	"\bauthInfo\x18\x02 \x01(\v2\x16.yuanbao_conn.AuthInfoR\bauthInfo\x128\n" +
	"\n" +
	"deviceInfo\x18\x03 \x01(\v2\x18.yuanbao_conn.DeviceInfoR\n" +
	"deviceInfo\x12=\n" +
	"\rcontainerInfo\x18\x04 \x01(\v2\x17.yuanbao_conn.ContainerR\rcontainerInfo\x12\x18\n" +
	"\aenvName\x18\x05 \x01(\tR\aenvName\x12\x1a\n" +
	"\bbindMode\x18\x06 \x01(\rR\bbindMode\x12\x1e\n" +
	"\n" +
	"forceToken\x18\a \x01(\tR\n" +
	"forceToken\"\x93\x01\n" +
	"\vAuthBindRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tconnectId\x18\x03 \x01(\tR\tconnectId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bclientIp\x18\x05 \x01(\tR\bclientIp\"\t\n" +
	"\aPingReq\"M\n" +
	"\aPingRsp\x12$\n" +
	"\rheartInterval\x18\x01 \x01(\rR\rheartInterval\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"f\n" +
	"\n" +
	"KickoutMsg\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12(\n" +
	"\x0fotherDeviceName\x18\x03 \x01(\tR\x0fotherDeviceName\".\n" +
	"\x04Meta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\rUpdateMetaReq\x120\n" +
	"\tmetaInfos\x18\x01 \x03(\v2\x12.yuanbao_conn.MetaR\tmetaInfos\"=\n" +
	"\rUpdateMetaRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\aPushMsg\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\tR\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data*\x99\x04\n" +
	"\aRetCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x12\n" +
	"\x0ePARAMS_INVALID\x10\x01\x12\r\n" +
	"\tAUTH_FAIL\x10\x02\x12\x11\n" +
	"\rUNKNOWN_ROUTE\x10\x03\x12\x10\n" +
	"\fALREADY_AUTH\x10\x04\x12\x17\n" +
	"\x13SAME_KIND_DEV_LOGIN\x10\x05\x12\x16\n" +
	"\x12AUTH_TOKEN_INVALID\x10\x06\x12\x16\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\a\x12\x1c\n" +
	"\x18AUTH_USER_NOT_REGISTERED\x10\b\x12\x17\n" +
	"\x13AUTH_USER_FORBIDDEN\x10\t\x12\x19\n" +
	"\x15AUTH_USER_UNQUALIFIED\x10\n" +
	"\x12 \n" +
	"\x1cAUTH_TOKEN_FORCED_EXPIRATION\x10\v\x12\x18\n" +
	"\x14PROHIBIT_APP_VERSION\x10\f\x12\x18\n" +
	"\x14PACKAGE_SIGN_ILLEGAL\x10\r\x12\x12\n" +
	"\x0eINNER_SVR_FAIL\x10\x0e\x12\x14\n" +
	"\x10OVERLOAD_CONTROL\x10\x0f\x12\x16\n" +
	"\x12SET_STATE_CONFLICT\x10\x10\x12\x13\n" +
	"\x0fCONN_OVER_LIMIT\x10\x11\x12\x12\n" +
	"\x0eNO_USER_ONLINE\x10\x12\x12\x10\n" +
	"\fPARTIAL_FAIL\x10\x13\x12\f\n" +
	"\bNET_FAIL\x10\x14\x12\x17\n" +
	"\x13BACKEND_RETURN_FAIL\x10\x15\x12\x10\n" +
	"\fUSER_OFFLINE\x10\x16\x12\x12\n" +
	"\x0eUSER_NOT_EXIST\x10\x17B\x19Z\x17yuanbao-go/wsproto/connb\x06proto3"

var (
	file_proto_conn_proto_rawDescOnce sync.Once
	file_proto_conn_proto_rawDescData []byte
)

func file_proto_conn_proto_rawDescGZIP() []byte {
	file_proto_conn_proto_rawDescOnce.Do(func() {
		file_proto_conn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_conn_proto_rawDesc), len(file_proto_conn_proto_rawDesc)))
	})
	return file_proto_conn_proto_rawDescData
}

var file_proto_conn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_conn_proto_goTypes = []any{
	(RetCode)(0),          // 0: yuanbao_conn.RetCode
	(*HeadMeta)(nil),      // 1: yuanbao_conn.HeadMeta
	(*Head)(nil),          // 2: yuanbao_conn.Head
	(*ConnMsg)(nil),       // 3: yuanbao_conn.ConnMsg
	(*DirectedPush)(nil),  // 4: yuanbao_conn.DirectedPush
	(*AuthInfo)(nil),      // 5: yuanbao_conn.AuthInfo
	(*DeviceInfo)(nil),    // 6: yuanbao_conn.DeviceInfo
	(*Container)(nil),     // 7: yuanbao_conn.Container
	(*AuthBindReq)(nil),   // 8: yuanbao_conn.AuthBindReq
	(*AuthBindRsp)(nil),   // 9: yuanbao_conn.AuthBindRsp
	(*PingReq)(nil),       // 10: yuanbao_conn.PingReq
	(*PingRsp)(nil),       // 11: yuanbao_conn.PingRsp
	(*KickoutMsg)(nil),    // 12: yuanbao_conn.KickoutMsg
	(*Meta)(nil),          // 13: yuanbao_conn.Meta
	(*UpdateMetaReq)(nil), // 14: yuanbao_conn.UpdateMetaReq
	(*UpdateMetaRsp)(nil), // 15: yuanbao_conn.UpdateMetaRsp
	(*PushMsg)(nil),       // 16: yuanbao_conn.PushMsg
}
var file_proto_conn_proto_depIdxs = []int32{
	1,  // 0: yuanbao_conn.Head.meta:type_name -> yuanbao_conn.HeadMeta
	2,  // 1: yuanbao_conn.ConnMsg.head:type_name -> yuanbao_conn.Head
	5,  // 2: yuanbao_conn.AuthBindReq.authInfo:type_name -> yuanbao_conn.AuthInfo
	6,  // 3: yuanbao_conn.AuthBindReq.deviceInfo:type_name -> yuanbao_conn.DeviceInfo
	7,  // 4: yuanbao_conn.AuthBindReq.containerInfo:type_name -> yuanbao_conn.Container
	13, // 5: yuanbao_conn.UpdateMetaReq.metaInfos:type_name -> yuanbao_conn.Meta
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_conn_proto_init() }
func file_proto_conn_proto_init() {
	if File_proto_conn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_conn_proto_rawDesc), len(file_proto_conn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_conn_proto_goTypes,
		DependencyIndexes: file_proto_conn_proto_depIdxs,
		EnumInfos:         file_proto_conn_proto_enumTypes,
		MessageInfos:      file_proto_conn_proto_msgTypes,
	}.Build()
	File_proto_conn_proto = out.File
	file_proto_conn_proto_goTypes = nil
	file_proto_conn_proto_depIdxs = nil
}
